version: '3.9'

services:
  postgres-db3:
    container_name: postgres3
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=casbin
    ports:
      - "5435:5432"
    volumes:
      - db:/data/postgres3
    networks:
      - healthserve

  
  api-service:
    container_name: api-gateway
    build: .
    depends_on:
      - postgres-db3
    ports:
      - "8080:8080"
    networks:
     - healthserve

networks:
  healthserve:
    external: true

volumes:
  db:
  